<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4022.18">
  <POU Name="MAIN" Id="{0324a35e-fdea-4e18-9862-ff85a207e95f}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
    fbMotionTstLab: FB_MotionStage;
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[//Run fb Motion Stage
fbMotionTstLab(stMotionStage:=GVL_Devices.M1);]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>